config/routes.rb
Rails.application.routes.draw do
  root :to => 'products#index'
  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, PhotoUploader

  validates :title, presence: true
  validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ProductsHelper

  # GET /products
  def index
    @products = Product.page(params[:page]).per(10).order("id DESC").limit(8)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /products/1
  def show
    @product = Product.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
   end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # POST /products
  def create
    @product = Product.create()
    @product.image =  params[:product][:image]
    @product.title = params[:product][:title]
    @product.deletekey = params[:product][:deletekey]

    respond_to do |format|
      if @product.save
        File.open "#{Rails.root}/public/stlFiles/#{@product.id}.stl", 'w' do |f|
          f.write Ochoko.create "#{Rails.root}/public" + @product.image.url.to_s
        end

        format.html { redirect_to @product, notice: 'Product was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # DELETE /products/1
  def destroy
    product = Product.find(params[:id])
    
    if product.deletekey == params[:code] then
      File.delete("#{Rails.root}/public" + product.image.url.to_s)
      File.delete("#{Rails.root}/public/stlFiles/#{product.id}.stl")
      product.destroy
      render :json => {'result' => true}
    else
      render :json => {'result' => false}
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
require_relative 'stl/util2d'
require_relative 'stl/stl'

module ProductsHelper

class Ochoko

  BASE_HEIGHT = 0.3
  CUP_HEIGHT = 1.5
  #THICKNESS = 0.15
  THICKNESS = 0.15
  W, H = 200, 200

  def self.create imgfile
    rand2d = Rand2D.new W, H, 0.1, 0.5
    texture = Texture.new imgfile

    line = -> t {
      r=0.8+0.4*(1-(1-t)**2)
      z=BASE_HEIGHT+CUP_HEIGHT*t
      [r,z]
    }

    stl = STL.new do
      pole W, H do |t1, z1|
        th = 2*Math::PI*t1
        if t = range(z1, 0..0.05)
          z2 = BASE_HEIGHT*t
          r2 = 0.9-0.1*t
        elsif t = range(z1, 0.05..0.75)
          r2, z2 = line.call t
          r2 -= THICKNESS/3*(1-texture.get(t1,1-t))
        elsif t = range(z1, 0.75..0.85)
          z2=CUP_HEIGHT+BASE_HEIGHT+Math.sin(Math::PI*t)*THICKNESS/2
          r2=1.2+(Math.cos(Math::PI*t)-1)*THICKNESS/2
        elsif t = range(z1, 0.85..1)
          r2, z2 = line.call 1-t
          r2 -= THICKNESS
        end
        rnd = 1+0.04*rand2d.get(t1, z2)
        {
          x: 20*rnd*r2*Math.cos(th),
          y: 20*rnd*r2*Math.sin(th),
          z: 20*z2
        }
      end
    end

    stl.data
  end
  
end

end

app/helpers/stl/stl.rb
class STL
  def initialize options={}, &block
    @buffer = []
    name = options[:name] || 'object'
    stlputs "solid #{name}"
    begin
      instance_eval &block
    ensure
      stlputs "endsolid #{name}"
    end
    if options && options[:io]
      options[:io].write data
    elsif options && options[:file]
      File.open(options[:file],'w'){|f|f.write data}
    end
  end

  def data
    @buffer.join "\n"
  end

  def range t, range
    (t-range.begin)/(range.end-range.begin) if range.include? t
  end

  def pole tlevel, zlevel, &block
    points=(0..zlevel).map{|z|
      (0...tlevel).map{|t|
        block.(t.fdiv(tlevel), z.fdiv(zlevel), tlevel, zlevel)
      }
    }
    [0, zlevel].each{|z|
      coords = points[z]
      center = Hash[[:x,:y,:z].map{|k|[k,coords.map{|p|p[k]}.inject(&:+)/tlevel]}]
      tlevel.times do |i|
        face center, coords[i-1], coords[i], z==0
      end
    }
    zlevel.times do |z0|
      z1 = z0 + 1
      tlevel.times do |t1|
        t0 = t1 - 1
        face points[z0][t0], points[z0][t1], points[z1][t0]
        face points[z1][t0], points[z0][t1], points[z1][t1]
      end
    end
  end

  private

  def stlputs str
    @buffer << str
  end

  def face p1,p2,p3,flip=false
    p2,p3=p3,p2 if flip
    stlputs "facet normal 0 0 0"
    stlputs "outer loop"
    [p1,p2,p3].each do |p|
      stlputs "vertex #{p[:x].round 4} #{p[:y].round 4} #{p[:z].round 4}"
    end
    stlputs "endloop"
    stlputs "endfacet"
  end

end

app/helpers/stl/util2d.rb
module Array2DGetter
  def [] x, y
    @data[x % width][y % height]
  end

  def get x, y
    #avoid bug ((-5e-17)%1).in?(0..1) => false
    ix,dx=(x%1%1*@width).divmod 1
    iy,dy=(y%1%1*@height).divmod 1
    jx=(ix+1) % @width
    jy=(iy+1) % @height
    @data[ix][iy]*(1-dx)*(1-dy)+
    @data[jx][iy]*dx*(1-dy)+
    @data[ix][jy]*(1-dx)*dy+
    @data[jx][jy]*dx*dy
  end
end

class Rand2D
  attr_reader :width, :height
  include Array2DGetter

  def initialize width, height, wscale, hscale = wscale
    @width, @height = width, height
    arr2d=height.times.map{
      width.times.map{2*rand-1}
    }.map{|line|
      Rand2D.smooth line, width*wscale
    }.transpose.map{|line|
      Rand2D.smooth line, height*hscale
    }
    deviation = Math.sqrt arr2d.map{|line|line.map{|x|x*x}.inject(:+)}.inject(:+)/width/height
    @data = arr2d.map{|line|line.map{|x|x/deviation}}
  end

  def self.smooth array, scale
    exp=->arr,e{
      z=0
      arr.each{|v|z=z*e+v}
      z*=1/(1-e**arr.size)
      arr.map{|v|z=z*e+v}
    }
    e=Math.exp(-3.0/scale)
    reversed=array.reverse
    sum1=exp.(array,e)
    sum2=exp.(array,e*e)
    rsum1=exp.(reversed,e).reverse
    rsum2=exp.(reversed,e*e).reverse
    array.size.times.map{|i|
      2*(sum1[i]+rsum1[i])-(sum2[i]+rsum2[i])-array[i]
    }
  end
end

class Texture
  attr_reader :width, :height
  include Array2DGetter

  def initialize file
    img = ChunkyPNG::Image.from_file file
    @width, @height = img.width, img.height
    @data = width.times.map{|x|
      height.times.map{|y|
        ChunkyPNG::Color.grayscale_teint(img[x,y]).fdiv(0xff)
      }
    }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnceTech</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" style="">
  <div class="navbar-header">
    <a class="navbar-brand" href="/"><%= image_tag "logo.png", :height => "100%" %></a>
  </div>
</nav>
<div class="jumbotron">
  <div class="container">
      <div style="height:10px;"></div>
      <%= yield %>
  </div>
</div>
<footer class="footer text-center">
  <p class="text-muted"><a href="https://twitter.com/motikan2010" target="_blank">@motikan2010</a> 2013 - </p>
</footer>
</body>
</html>

app/views/products/index.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-default">
      <div class="panel-body">
        <img class="img-thumbnail" width="100%" src="<%= asset_path "top.png" %>">
        <%= link_to 'Go to Create', new_product_path, :id => "create-btn", :class => 'btn btn-lg btn-success col-md-10 col-md-offset-1'%>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-default">
      <div class="panel-heading top-block-head">
        <h2><span class="glyphicon glyphicon-film" aria-hidden="true"></span> DEMO MOVIE</h2>
      </div>
      <div class="panel-body">
        <iframe src="//player.vimeo.com/video/86807850" width="100%" height="422" frameborder="0" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-default">
      <div class="panel-heading top-block-head">
        <h3><span class="glyphicon glyphicon-star" aria-hidden="true"></span> RECENT MODELS</h3>
      </div>
      <div class="panel-body">
        <div class="paging">
          <%= paginate(@products) %>
        </div>
        <% @products.each_with_index do |product, i| %>
            <% if i % 2 == 0 %>
                <div class="row row-eq-height">
            <% end %>
            <div class="col-md-6">
              <div class="product_div">
                <div class="product_image_div">
                  <%= image_tag product.image.url, :class => "product_image" %>
                </div>
                <div class="product_title_div">
                  <h2><%= product.title %></h2>
                  <%= link_to 'Show', product, :class => 'btn btn-primary' %>
                </div>
              </div>
            </div>
            <% if i % 2 == 1 || i + 1 ==  @products.length %>
                </div>
            <% end %>
        <% end %>
        <div class="paging">
          <%= paginate(@products) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="row">
    <div class="panel panel-default">
    <div class="panel-heading"></div>
      <div class="panel-body">
        <div class="col-md-8 col-md-offset-2">
          <%= form_for @product, :html => { :class => "form-horizontal" ,:multipart => true } do |f| %>
              <div class="row">
                <div class="col-md-12">
                  <div id="image-preview"></div>
                  <% if @product.errors.any? %>
                      <div class="alert alert-danger">
                        <ul>
                          <% @product.errors.full_messages.each do |msg| %>
                              <li><%= msg %></li>
                          <% end %>
                        </ul>
                      </div>
                  <% end %>
                </div>
              </div>
              <div class="form-group">
                <div class="col-md-12">
                <%= f.label :title %>
                <%= f.text_field :title, :class => 'form-control' %>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <%= f.label 'Base Model' %>
                  <%= select_tag 'model[type]', options_for_select({"Mini Cup" => "0", "Mini Pot" => "1"}), :class => 'form-control' %>
                </div>
                <div class="col-md-6">
                  <%= f.label "Delete Code" %>
                  <%= f.text_field :deletekey, placeholder: 'Use to Delete.', :class => 'form-control' %>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3">
                  <label class="input-group-btn">
                    <span class="btn btn-primary">
                      Select Image File <%= file_field_tag 'product[image]', :style => "display:none" %>
                    </span>
                  </label>
                </div>
                <div class="col-md-9">
                  <input id="file-name" type="text" class="form-control" disabled />
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <%= submit_tag "Create", {id: "submit_button", :class => "btn btn-success btn-lg"} %>
                </div>
              </div>
          <% end %>
        </div>
      </div>
      <div class="panel-footer"></div>
    </div>
  </div>
</div>

<script>
$(document).on('change', ':file', function() {
  var files = !!this.files ? this.files : [];
  if (!files.length || !window.FileReader) {
    return;
  }
  // 画像ファイル名を表示
  $('#file-name').val($(this).prop('files')[0].name);
  if (/^image/.test(files[0].type)) {
    var reader = new FileReader();
    reader.readAsDataURL(files[0]);
    reader.onloadend = function() {
      $('#image-preview').css("background-image", "url(" + this.result + ")");
    }
  }
});
</script>

app/views/products/show.html.erb
<div class="row row-eq-height">
  <div class="col-md-7 col-md-offset-1">
    <!-- Model Viewer -->
    <div id="model-viewer" class="row">
      <div class="panel panel-default">
        <div class="panel-heading"></div>
        <div class="panel-body text-center">
          <canvas id="cv" width="620" height="600"></canvas>
        </div>
        <div class="panel-footer"></div>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <!-- Model Operator -->
    <div id="model-operator" class="row">
      <div class="panel panel-default">
        <div class="panel-heading"></div>
        <div class="panel-body">
          <div class="row text-center">
            <h4><%= @product.title %></h4>
            <%= image_tag @product.image.to_s, :class => "img-thumbnail", :width => "100%" %>
          </div>

          <div class="row text-center">
            <%= link_to "Download", "/stlFiles/" + (@product.id.to_s) + ".stl",
                        class: "btn btn-info btn-large", style: "width:230px;", download: @product.id.to_s + ".stl" %>
          </div>
          <div class="row">
            <div class="col-md-6">
              <%= label_tag 'Model' %>
              <%= color_field "color", "model", :value => "#00ff00", :class => "form-control" %>
            </div>
            <div class="col-md-6">
              <%= label_tag 'Quality' %>
              <%= select :model, :quality, [["High", "high"], ["Medium", "medium"], ["Low", "low"]],
                         {:selected => "medium"}, {:class => "form-control"} %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <%= label_tag 'Back Top' %>
              <%= color_field "color", "back1", :value => "#ffffff", :class => "form-control" %>
            </div>
            <div class="col-md-6">
              <%= label_tag 'Back Bottom' %>
              <%= color_field "color", "back2", :value => "#515151", :class => "form-control" %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 col-md-offset-8">
              <%= button_tag "Delete", {:id => "delete", :class => "btn btn-danger"} %>
            </div>
          </div>
        </div>
        <div class="panel-footer"></div>
      </div>
    </div>

    <!-- Tips -->
    <div id="viewer-tip" class="row">
      <div class="well well-sm">
        Drag mouse to rotate <br/> Drag mouse with [Shift pressed] to zoom
        <h4><small># This web application do not support the InternetExplorer</small></h4>
      </div>
    </div>

  </div>
</div>

<script type="text/javascript">
$(function(){
  openByGet();

  $('#color_model').change(function(){
    changeOption('ModelColor', $(this).val());
  });

  $('#color_back1').change(function(){
    changeOption('BackgroundColor1', $(this).val());
  });

  $('#color_back2').change(function(){
    changeOption('BackgroundColor2', $(this).val());
  });

  $('#model_quality').change(function(){
    changeOption('Definition', $(this).val());
  });

  $('#delete').click(function(){
    var deleteCode = prompt();
    if(deleteCode){
      $.ajax({
        type: 'POST',
        url: '<%= product_path(@product) %>',
        data: '_method=delete&code=' + deleteCode,
        success: function(data){
          if(data.result){
            alert("Delete Complete.");
            location.href = '<%= products_path %>';
          }else{
            alert('No match Delete code.');
          }
        }
      });
    }else{

    }
  });
});

var viewer3d;

function getOptions(){
  var mc = document.getElementById("color_model").value;
  var bc1 = document.getElementById("color_back1").value;
  var bc2 = document.getElementById("color_back2").value;
  var ren = 'Flat';
  var def = document.getElementById("model_quality").value;
  return {
    ModelColor: mc,
    BackgroundColor1: bc1,
    BackgroundColor2: bc2,
    RenderMode: ren,
    Definition: def
  };
}

function readSTLfile(opt){
  var canvas = document.getElementById('cv');
  viewer3d = new JSC3D.Viewer(canvas);
  viewer3d.setParameter('SceneUrl', opt.SceneUrl);
  viewer3d.setParameter('InitRotationX', -80);
  viewer3d.setParameter('InitRotationY', 0);
  viewer3d.setParameter('InitRotationZ', 0);
  viewer3d.setParameter('ModelColor', opt.ModelColor);
  viewer3d.setParameter('BackgroundColor1', opt.BackgroundColor1);
  viewer3d.setParameter('BackgroundColor2', opt.BackgroundColor2);
  viewer3d.setParameter('RenderMode', opt.RenderMode);
  viewer3d.setParameter('Definition', opt.Definition);
  viewer3d.init();
  viewer3d.update();
}

function changeOption(strOpt, strValue){
  viewer3d.setParameter(strOpt, strValue);
  viewer3d.init();
  viewer3d.update();
}

function openByGet(){
  var url = '/stlFiles/<%= @product.id %>.stl';
  var opt = getOptions();
  opt.SceneUrl = url;
  readSTLfile(opt);
}
</script>